#!/usr/bin/env bash
# TempleEx Build Script (Linux/macOS)
# Combines all src/ modules into TempleEx-full.lua
# Usage: ./build.sh

set -euo pipefail

MODULES=(
    "yaml"
    "executor"
    "log"
    "config"
    "theme"
    "core"
    "core_functions"
    "shell"
    "autoload"
    "git"
    "ai"
    "api"
)

HEADER="--[[
    TempleEx - Full Build (Single File)
    Auto-generated by build.sh
    DO NOT EDIT DIRECTLY - edit src/ modules instead
]]

"

MODULE_LOADER="
local TempleExModules = {}
local TempleExModuleCache = {}

local function TempleExRequire(name)
    if TempleExModuleCache[name] then return TempleExModuleCache[name] end
    local mod = TempleExModules[name]
    if not mod then error(\"Module not found: \" .. name) end
    local result = mod()
    TempleExModuleCache[name] = result
    return result
end

"

OUTPUT="$HEADER$MODULE_LOADER"

echo "Building TempleEx-full.lua..."

for name in "${MODULES[@]}"; do
    path="src/${name}.lua"
    if [[ -f "$path" ]]; then
        content=$(cat "$path")
        # Replace require(script.Parent.xxx) with TempleExRequire("xxx")
        content="${content//require(\".\//\\([^\"]*\\)\")/TempleExRequire(\"\1\")}"
        content="${content//require[[:space:]]*([[:space:]]*script%.Parent%.\([[:alnum:]_]*\)[[:space:]]*)/TempleExRequire(\"\1\")}"
        # More robust replacement using sed
        content=$(echo "$content" | sed -E 's/require\("\.?\/([^"]+)"\)/TempleExRequire("\1")/g')
        content=$(echo "$content" | sed -E 's/require%s*\(?%s*script\.Parent\.([[:alnum:]_]+)%s*\)?/TempleExRequire("\1")/g')
        
        OUTPUT+="-- Module: ${name}\n${content}\n\n"
        echo "  Added module: ${name}"
    else
        echo "  WARNING: Module not found: ${path}" >&2
    fi
done

# Main entry point
MAIN='
-- ═══════════════════════════════════════════════════════════════
-- MAIN ENTRY POINT
-- ═══════════════════════════════════════════════════════════════

local TempleEx = {}
TempleEx.version = {major = 1, minor = 0, patch = 0}

-- Initialize subsystems in order
local function init()
    -- Config first (needs workspace path)
    local Config = TempleExRequire("config")
    Config.init(".")

    -- Theme engine
    local ThemeEngine = TempleExRequire("theme")
    ThemeEngine.loadAllThemes(Config.get("paths.themes") or "themes")
    local activeTheme = Config.get("theme.active") or "midnight-temple"
    ThemeEngine.applyTheme(activeTheme)

    -- Core functions
    local Core = TempleExRequire("core")
    TempleExRequire("core_functions") -- registers modules
    Core.loadState(Config.data)

    -- Shell (WM, MenuBar, Dock)
    local Shell = TempleExRequire("shell")
    Shell.init()

    -- Autoload
    local Autoload = TempleExRequire("autoload")
    Autoload.init()

    -- Git layer
    local Git = TempleExRequire("git")
    Git.startAutoUpdateLoop()

    -- AI agents
    local AI = TempleExRequire("ai")

    -- API
    local TempleApi = TempleExRequire("api")
    TempleApi.init()

    -- Expose subsystems on TempleEx
    TempleEx.Config = Config
    TempleEx.ThemeEngine = ThemeEngine
    TempleEx.Core = Core
    TempleEx.Shell = Shell
    TempleEx.Autoload = Autoload
    TempleEx.Git = Git
    TempleEx.AI = AI
    TempleEx.Api = TempleApi

    -- Global access for scripts
    _G.TempleEx = TempleEx
    _G.TempleApi = TempleApi
    _G.Temple = TempleApi

    return TempleEx
end

local ok, result = pcall(init)
if not ok then
    error("[TempleEx] Initialization failed: " .. tostring(result))
end

return result
'

OUTPUT+="$MAIN"

# Write full build
echo "$OUTPUT" > TempleEx-full.lua
echo "Built TempleEx-full.lua ($(wc -c < TempleEx-full.lua) bytes)"

# Update bootloader version
if [[ -f "TempleEx.lua" ]]; then
    sed -i 's/local BOOTLOADER_VERSION = "[0-9.]*"/local BOOTLOADER_VERSION = "1.0.0"/' TempleEx.lua
    echo "Updated TempleEx.lua bootloader version"
fi

echo "Build complete!"