# TempleEx Build Script (PowerShell)
# 1) Generates src/assets.lua (embeds themes/ + agents/ so one loadstring works offline)
# 2) Concatenates src/*.lua into TempleEx-full.lua (single-file build)

$ErrorActionPreference = "Stop"

# ── Single source of truth for the version ─────────────────────
$Version = "1.2.0"
$vmaj, $vmin, $vpat = $Version.Split(".")

# Write UTF-8 WITHOUT BOM (PowerShell 5.1's Set-Content -Encoding UTF8 adds a BOM,
# which breaks Luau's loadstring with "Expected identifier ... U+feff").
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
function Write-NoBom([string]$path, [string]$text) {
    # Strip any leading BOM from the text itself before writing
    if ($text.Length -gt 0 -and $text[0] -eq [char]0xFEFF) { $text = $text.Substring(1) }
    [System.IO.File]::WriteAllBytes($path, $Utf8NoBom.GetBytes($text))
}

# ── Step 1: generate src/assets.lua ────────────────────────────
$assetFiles = @()
$assetFiles += Get-ChildItem "themes" -Filter "*.yaml" -ErrorAction SilentlyContinue
$assetFiles += Get-ChildItem "agents" -Filter "*.md" -ErrorAction SilentlyContinue

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- AUTO-GENERATED by build.ps1 from themes/ and agents/. Do not edit.")
[void]$sb.AppendLine("local Assets = {}")
[void]$sb.AppendLine("Assets.files = {}")
foreach ($f in $assetFiles) {
    $rel = ($f.Directory.Name + "/" + $f.Name) -replace '\\','/'
    $content = Get-Content $f.FullName -Raw -Encoding UTF8
    # [==[ ... ]==] long string is safe: YAML/MD here never contain ]==] or [==[
    [void]$sb.AppendLine('Assets.files["' + $rel + '"] = [==[')
    [void]$sb.AppendLine($content)
    [void]$sb.AppendLine("]==]")
}
[void]$sb.AppendLine(@"
-- Write embedded assets into the executor workspace if missing.
-- base is the workspace path ('' = executor workspace root).
function Assets.materialize(base)
    local Executor = TempleExRequire("executor")
    local written = 0
    for relPath, content in pairs(Assets.files) do
        local full = (base == nil or base == "") and relPath or (base .. "/" .. relPath)
        local _, exists = Executor.fs_exists(full)
        if not exists then
            local dir = relPath:match("^(.+)/[^/]+$")
            if dir then
                local dfull = (base == nil or base == "") and dir or (base .. "/" .. dir)
                pcall(Executor.fs_mkdir, dfull)
            end
            local ok = Executor.fs_write(full, content)
            if ok then written = written + 1 end
        end
    end
    return written
end

return Assets
"@)

Write-NoBom "src/assets.lua" $sb.ToString()
Write-Host "Generated src/assets.lua ($($assetFiles.Count) embedded files)"

# ── Step 2: concatenate modules ────────────────────────────────
$modules = @("yaml", "executor", "log", "assets", "config", "theme", "core", "core_functions", "icons", "shell", "autoload", "git", "ai", "api")

$header = @"
--[[
    TempleEx - Full Build (Single File)
    Auto-generated by build.ps1
    DO NOT EDIT DIRECTLY - edit src/ modules instead
]]

"@

$moduleLoader = @"
local TempleExModules = {}
local TempleExModuleCache = {}

local function TempleExRequire(name)
    if TempleExModuleCache[name] then return TempleExModuleCache[name] end
    local mod = TempleExModules[name]
    if not mod then error("Module not found: " .. name) end
    local result = mod()
    TempleExModuleCache[name] = result
    return result
end

"@

$output = $header + $moduleLoader

foreach ($name in $modules) {
    $path = "src\$name.lua"
    if (Test-Path $path) {
        $content = Get-Content $path -Raw -Encoding UTF8
        # Strip any leading BOM that survived reading
        $content = $content.TrimStart([char]0xFEFF)
        # Replace require(script.Parent.xxx) with TempleExRequire("xxx")
        $content = $content -replace 'require\s*\(\s*script\.Parent\.(\w+)\s*\)', 'TempleExRequire("$1")'
        # Wrap the module body in a function registered in TempleExModules.
        # The module's trailing `return X` becomes this function's return value.
        $output += "TempleExModules[`"$name`"] = function()`n" + $content + "`nend`n`n"
        Write-Host "  Added module: $name"
    } else {
        Write-Warning "Module not found: $path"
    }
}

$main = @"
-- ═══════════════════════════════════════════════════════════════
-- MAIN ENTRY POINT
-- ═══════════════════════════════════════════════════════════════

local TempleEx = {}
TempleEx.version = {major = 1, minor = 0, patch = 0}

local function init()
    -- Materialize embedded themes/agents into workspace (offline-ready)
    local Assets = TempleExRequire("assets")
    pcall(Assets.materialize, "")

    -- Config first (needs workspace path)
    local Config = TempleExRequire("config")
    Config.init("")

    -- Theme engine
    local ThemeEngine = TempleExRequire("theme")
    ThemeEngine.loadAllThemes(Config.get("paths.themes") or "themes")
    local activeTheme = Config.get("theme.active") or "midnight-temple"
    ThemeEngine.applyTheme(activeTheme)
    if Config.get("theme.auto_reload") then
        ThemeEngine.startWatch(Config.get("paths.themes") or "themes")
    end

    -- Core functions
    local Core = TempleExRequire("core")
    TempleExRequire("core_functions") -- registers modules
    Core.loadState(Config.data)

    -- Shell (WM, MenuBar, Dock)
    local Shell = TempleExRequire("shell")
    Shell.init()

    -- Autoload
    local Autoload = TempleExRequire("autoload")
    Autoload.init()

    -- Git layer
    local Git = TempleExRequire("git")
    Git.startAutoUpdateLoop()

    -- AI agents
    local AI = TempleExRequire("ai")

    -- API
    local TempleApi = TempleExRequire("api")
    TempleApi.init()

    TempleEx.Config = Config
    TempleEx.ThemeEngine = ThemeEngine
    TempleEx.Core = Core
    TempleEx.Shell = Shell
    TempleEx.Autoload = Autoload
    TempleEx.Git = Git
    TempleEx.AI = AI
    TempleEx.Api = TempleApi
    TempleEx.Assets = Assets
    TempleEx.Icons = TempleExRequire("icons")

    _G.TempleEx = TempleEx
    _G.TempleApi = TempleApi
    _G.Temple = TempleApi

    return TempleEx
end

local ok, result = pcall(init)
if not ok then
    error("[TempleEx] Initialization failed: " .. tostring(result))
end

return result
"@

$output += $main

# Stamp the single-source version into every place the build hardcodes it.
$output = $output -replace 'TempleEx\.version = \{major = \d+, minor = \d+, patch = \d+\}', "TempleEx.version = {major = $vmaj, minor = $vmin, patch = $vpat}"
$output = $output -replace 'TempleApi\.version = \{major = \d+, minor = \d+, patch = \d+\}', "TempleApi.version = {major = $vmaj, minor = $vmin, patch = $vpat}"
$output = $output -replace 'Git\.currentVersion = "[\d.]+"', "Git.currentVersion = `"$Version`""

Write-NoBom "TempleEx-full.lua" $output
Write-Host "Built TempleEx-full.lua ($((Get-Item 'TempleEx-full.lua').Length) bytes) v$Version"

# Update bootloader version
if (Test-Path "TempleEx.lua") {
    $bootloader = Get-Content "TempleEx.lua" -Raw -Encoding UTF8
    $bootloader = $bootloader -replace 'local BOOTLOADER_VERSION = "[\d.]+"', "local BOOTLOADER_VERSION = `"$Version`""
    Write-NoBom "TempleEx.lua" $bootloader
    Write-Host "Updated TempleEx.lua bootloader version to v$Version"
}

Write-Host "Build complete!"
