--[[
    TempleEx Build Script
    Combines all src/ modules into TempleEx-full.lua
    Run with: lua build.lua (requires Lua 5.1+)
]]

local function readFile(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local content = f:read("*a")
    f:close()
    return content
end

local function writeFile(path, content)
    local f = io.open(path, "w")
    if not f then return false end
    f:write(content)
    f:close()
    return true
end

local modules = {
    "yaml",
    "executor",
    "log",
    "config",
    "theme",
    "core",
    "core_functions",
    "shell",
    "autoload",
    "git",
    "ai",
    "api"
}

local header = [[--[[
    TempleEx - Full Build (Single File)
    Auto-generated by build.lua
    DO NOT EDIT DIRECTLY - edit src/ modules instead
]]

local function wrapModule(name, content)
    -- Remove the trailing `return X` and wrap in a module loader
    -- For single-file build, we'll use a simple module system
    return string.format([[
-- Module: %s
%s
]], name, content)
end

local parts = {header}

-- Module registry
table.insert(parts, [[
local TempleExModules = {}
local TempleExModuleCache = {}

local function TempleExRequire(name)
    if TempleExModuleCache[name] then return TempleExModuleCache[name] end
    local mod = TempleExModules[name]
    if not mod then error("Module not found: " .. name) end
    local result = mod()
    TempleExModuleCache[name] = result
    return result
end

]])

-- Load each module
for _, name in ipairs(modules) do
    local content = readFile("src/" .. name .. ".lua")
    if content then
        -- Wrap in a function that returns the module
        -- Need to replace `require(script.Parent.xxx)` with `TempleExRequire("xxx")`
        content = content:gsub('require%("%./([^"]+)%)', 'TempleExRequire("%1")')
        content = content:gsub('require%s*%(?%s*script%.Parent%.([%w_]+)%s*%)?', 'TempleExRequire("%1")')

        table.insert(parts, string.format('TempleExModules["%s"] = function()\n%s\nend\n', name, content))
    else
        print("WARNING: Module not found: src/" .. name .. ".lua")
    end
end

-- Main entry point that initializes everything
table.insert(parts, [[
-- ═══════════════════════════════════════════════════════════════
-- MAIN ENTRY POINT
-- ═══════════════════════════════════════════════════════════════

local TempleEx = {}
TempleEx.version = {major = 1, minor = 0, patch = 0}

-- Initialize subsystems in order
local function init()
    -- Config first (needs workspace path)
    local Config = TempleExRequire("config")
    Config.init(".")

    -- Theme engine
    local ThemeEngine = TempleExRequire("theme")
    ThemeEngine.loadAllThemes(Config.get("paths.themes") or "themes")
    local activeTheme = Config.get("theme.active") or "midnight-temple"
    ThemeEngine.applyTheme(activeTheme)

    -- Core functions
    local Core = TempleExRequire("core")
    TempleExRequire("core_functions") -- registers modules
    Core.loadState(Config.data)

    -- Shell (WM, MenuBar, Dock)
    local Shell = TempleExRequire("shell")
    Shell.init()

    -- Autoload
    local Autoload = TempleExRequire("autoload")
    Autoload.init()

    -- Git layer
    local Git = TempleExRequire("git")
    Git.startAutoUpdateLoop()

    -- AI agents
    local AI = TempleExRequire("ai")

    -- API
    local TempleApi = TempleExRequire("api")
    TempleApi.init()

    -- Expose subsystems on TempleEx
    TempleEx.Config = Config
    TempleEx.ThemeEngine = ThemeEngine
    TempleEx.Core = Core
    TempleEx.Shell = Shell
    TempleEx.Autoload = Autoload
    TempleEx.Git = Git
    TempleEx.AI = AI
    TempleEx.Api = TempleApi

    -- Global access for scripts
    _G.TempleEx = TempleEx
    _G.TempleApi = TempleApi
    _G.Temple = TempleApi

    return TempleEx
end

local ok, result = pcall(init)
if not ok then
    error("[TempleEx] Initialization failed: " .. tostring(result))
end

return result
]])

local fullBuild = table.concat(parts, "\n")

-- Write output
writeFile("TempleEx-full.lua", fullBuild)
print("Built TempleEx-full.lua (" .. #fullBuild .. " bytes)")

-- Also create a minimal bootloader check
local bootloader = readFile("TempleEx.lua")
if bootloader then
    -- Update version in bootloader
    local version = "1.0.0"
    bootloader = bootloader:gsub('local BOOTLOADER_VERSION = "[%d%.]+"', 'local BOOTLOADER_VERSION = "' .. version .. '"')
    writeFile("TempleEx.lua", bootloader)
    print("Updated TempleEx.lua bootloader version")
end

print("Build complete!")