#!/usr/bin/env bash
# TempleEx Build Script (Bash)
# 1) Generates src/assets.lua (embeds themes/ + agents/ so one loadstring works offline)
# 2) Concatenates src/*.lua into TempleEx-full.lua (single-file build)

set -e

# ── Step 1: generate src/assets.lua ────────────────────────────
{
    echo "-- AUTO-GENERATED by build.sh from themes/ and agents/. Do not edit."
    echo "local Assets = {}"
    echo "Assets.files = {}"
    for f in themes/*.yaml agents/*.md; do
        [ -f "$f" ] || continue
        rel="$(basename "$(dirname "$f")")/$(basename "$f")"
        echo "Assets.files[\"$rel\"] = [==["
        sed -E '1s/^\xEF\xBB\xBF//' "$f"
        echo "]==]"
    done
    cat <<'MATERIALIZER'
-- Write embedded assets into the executor workspace if missing.
function Assets.materialize(base)
    local Executor = TempleExRequire("executor")
    local written = 0
    for relPath, content in pairs(Assets.files) do
        local full = (base == nil or base == "") and relPath or (base .. "/" .. relPath)
        local _, exists = Executor.fs_exists(full)
        if not exists then
            local dir = relPath:match("^(.+)/[^/]+$")
            if dir then
                local dfull = (base == nil or base == "") and dir or (base .. "/" .. dir)
                pcall(Executor.fs_mkdir, dfull)
            end
            local ok = Executor.fs_write(full, content)
            if ok then written = written + 1 end
        end
    end
    return written
end

return Assets
MATERIALIZER
} > src/assets.lua
echo "Generated src/assets.lua"

# ── Step 2: concatenate modules ────────────────────────────────
MODULES=(yaml executor log assets config theme core core_functions shell autoload git ai api)

OUTPUT="--[[
    TempleEx - Full Build (Single File)
    Auto-generated by build.sh
    DO NOT EDIT DIRECTLY - edit src/ modules instead
]]

local TempleExModules = {}
local TempleExModuleCache = {}

local function TempleExRequire(name)
    if TempleExModuleCache[name] then return TempleExModuleCache[name] end
    local mod = TempleExModules[name]
    if not mod then error(\"Module not found: \" .. name) end
    local result = mod()
    TempleExModuleCache[name] = result
    return result
end

"

for name in "${MODULES[@]}"; do
    path="src/${name}.lua"
    if [ -f "$path" ]; then
        content=$(sed -E -e '1s/^\xEF\xBB\xBF//' -e 's/require[[:space:]]*\([[:space:]]*script\.Parent\.([[:alnum:]_]+)[[:space:]]*\)/TempleExRequire("\1")/g' "$path")
        OUTPUT+="-- Module: ${name}
${content}

"
        echo "  Added module: ${name}"
    else
        echo "  Warning: Module not found: ${path}"
    fi
done

OUTPUT+="-- ═══════════════════════════════════════════════════════════════
-- MAIN ENTRY POINT
-- ═══════════════════════════════════════════════════════════════

local TempleEx = {}
TempleEx.version = {major = 1, minor = 0, patch = 0}

local function init()
    local Assets = TempleExRequire(\"assets\")
    pcall(Assets.materialize, \"\")

    local Config = TempleExRequire(\"config\")
    Config.init(\"\")

    local ThemeEngine = TempleExRequire(\"theme\")
    ThemeEngine.loadAllThemes(Config.get(\"paths.themes\") or \"themes\")
    local activeTheme = Config.get(\"theme.active\") or \"midnight-temple\"
    ThemeEngine.applyTheme(activeTheme)
    if Config.get(\"theme.auto_reload\") then
        ThemeEngine.startWatch(Config.get(\"paths.themes\") or \"themes\")
    end

    local Core = TempleExRequire(\"core\")
    TempleExRequire(\"core_functions\")
    Core.loadState(Config.data)

    local Shell = TempleExRequire(\"shell\")
    Shell.init()

    local Autoload = TempleExRequire(\"autoload\")
    Autoload.init()

    local Git = TempleExRequire(\"git\")
    Git.startAutoUpdateLoop()

    local AI = TempleExRequire(\"ai\")

    local TempleApi = TempleExRequire(\"api\")
    TempleApi.init()

    TempleEx.Config = Config
    TempleEx.ThemeEngine = ThemeEngine
    TempleEx.Core = Core
    TempleEx.Shell = Shell
    TempleEx.Autoload = Autoload
    TempleEx.Git = Git
    TempleEx.AI = AI
    TempleEx.Api = TempleApi
    TempleEx.Assets = Assets

    _G.TempleEx = TempleEx
    _G.TempleApi = TempleApi
    _G.Temple = TempleApi

    return TempleEx
end

local ok, result = pcall(init)
if not ok then
    error(\"[TempleEx] Initialization failed: \" .. tostring(result))
end

return result
"

echo "$OUTPUT" > TempleEx-full.lua
echo "Built TempleEx-full.lua ($(wc -c < TempleEx-full.lua) bytes)"

# Update bootloader version
if [ -f "TempleEx.lua" ]; then
    sed -i 's/local BOOTLOADER_VERSION = "[^"]*"/local BOOTLOADER_VERSION = "1.0.0"/' TempleEx.lua
    echo "Updated TempleEx.lua bootloader version"
fi

echo "Build complete!"
