# TempleEx Build Script (PowerShell)
# Combines all src/ modules into TempleEx-full.lua

$modules = @("yaml", "executor", "log", "config", "theme", "core", "core_functions", "shell", "autoload", "git", "ai", "api")

$header = @"
--[[
    TempleEx - Full Build (Single File)
    Auto-generated by build.ps1
    DO NOT EDIT DIRECTLY - edit src/ modules instead
]]

"@

$moduleLoader = @"
local TempleExModules = {}
local TempleExModuleCache = {}

local function TempleExRequire(name)
    if TempleExModuleCache[name] then return TempleExModuleCache[name] end
    local mod = TempleExModules[name]
    if not mod then error("Module not found: " .. name) end
    local result = mod()
    TempleExModuleCache[name] = result
    return result
end

"@

$output = $header + $moduleLoader

foreach ($name in $modules) {
    $path = "src\$name.lua"
    if (Test-Path $path) {
        $content = Get-Content $path -Raw -Encoding UTF8
        # Replace require(script.Parent.xxx) with TempleExRequire("xxx")
        $content = $content -replace 'require\("%\./([^"]+)"\)', 'TempleExRequire("$1")'
        $content = $content -replace 'require%s*\(?%s*script%.Parent%.([%w_]+)%s*\)?', 'TempleExRequire("$1")'
        $output += "-- Module: $name`n" + $content + "`n`n"
        Write-Host "Added module: $name"
    } else {
        Write-Warning "Module not found: $path"
    }
}

# Main entry point
$main = @"
-- ═══════════════════════════════════════════════════════════════
-- MAIN ENTRY POINT
-- ═══════════════════════════════════════════════════════════════

local TempleEx = {}
TempleEx.version = {major = 1, minor = 0, patch = 0}

-- Initialize subsystems in order
local function init()
    -- Config first (needs workspace path)
    local Config = TempleExRequire("config")
    Config.init(".")

    -- Theme engine
    local ThemeEngine = TempleExRequire("theme")
    ThemeEngine.loadAllThemes(Config.get("paths.themes") or "themes")
    local activeTheme = Config.get("theme.active") or "midnight-temple"
    ThemeEngine.applyTheme(activeTheme)

    -- Core functions
    local Core = TempleExRequire("core")
    TempleExRequire("core_functions") -- registers modules
    Core.loadState(Config.data)

    -- Shell (WM, MenuBar, Dock)
    local Shell = TempleExRequire("shell")
    Shell.init()

    -- Autoload
    local Autoload = TempleExRequire("autoload")
    Autoload.init()

    -- Git layer
    local Git = TempleExRequire("git")
    Git.startAutoUpdateLoop()

    -- AI agents
    local AI = TempleExRequire("ai")

    -- API
    local TempleApi = TempleExRequire("api")
    TempleApi.init()

    -- Expose subsystems on TempleEx
    TempleEx.Config = Config
    TempleEx.ThemeEngine = ThemeEngine
    TempleEx.Core = Core
    TempleEx.Shell = Shell
    TempleEx.Autoload = Autoload
    TempleEx.Git = Git
    TempleEx.AI = AI
    TempleEx.Api = TempleApi

    -- Global access for scripts
    _G.TempleEx = TempleEx
    _G.TempleApi = TempleApi
    _G.Temple = TempleApi

    return TempleEx
end

local ok, result = pcall(init)
if not ok then
    error("[TempleEx] Initialization failed: " .. tostring(result))
end

return result
"@

$output += $main

# Write full build
$output | Set-Content "TempleEx-full.lua" -Encoding UTF8
Write-Host "Built TempleEx-full.lua ($($output.Length) bytes)"

# Update bootloader version
$bootloader = Get-Content "TempleEx.lua" -Raw -Encoding UTF8
$bootloader = $bootloader -replace 'local BOOTLOADER_VERSION = "[\d.]+ "', 'local BOOTLOADER_VERSION = "1.0.0"'
$bootloader | Set-Content "TempleEx.lua" -Encoding UTF8
Write-Host "Updated TempleEx.lua bootloader version"

Write-Host "Build complete!"